export interface User {
  _id: string;
  email: string;
  displayName: string;
  bio: string;
  avatarUrl: string;
  createdAt: string;
  updatedAt: string;
  token?: string; // Token is optional here as it's not always present
}

export interface Completion {
  _id?: string; // Optional because it's generated by MongoDB
  date: string; // Store as ISO string e.g., '2025-08-05T00:00:00.000Z'
}

export interface Habit {
  _id: string;
  user: string; // User ID
  name: string;
  description?: string;
  color: string;
  completions: Completion[];
  createdAt: string;
}